/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/movies/': RouteRecordInfo<'/movies/', '/movies', Record<never, never>, Record<never, never>>,
    '/movies/formAction/': RouteRecordInfo<'/movies/formAction/', '/movies/formAction', Record<never, never>, Record<never, never>>,
    '/movies/formAction/ActorsTable': RouteRecordInfo<'/movies/formAction/ActorsTable', '/movies/formAction/ActorsTable', Record<never, never>, Record<never, never>>,
    '/movies/view/': RouteRecordInfo<'/movies/view/', '/movies/view', Record<never, never>, Record<never, never>>,
  }
}
